
package dinhnguyen.techs.convert.mapper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CountryPortService", targetNamespace = "http://locahost:8090", wsdlLocation = "http://localhost:8090/soap/country.wsdl")
public class CountryPortService
    extends Service
{

    private final static URL COUNTRYPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYPORTSERVICE_EXCEPTION;
    private final static QName COUNTRYPORTSERVICE_QNAME = new QName("http://locahost:8090", "CountryPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/soap/country.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYPORTSERVICE_WSDL_LOCATION = url;
        COUNTRYPORTSERVICE_EXCEPTION = e;
    }

    public CountryPortService() {
        super(__getWsdlLocation(), COUNTRYPORTSERVICE_QNAME);
    }

    public CountryPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYPORTSERVICE_QNAME, features);
    }

    public CountryPortService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYPORTSERVICE_QNAME);
    }

    public CountryPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYPORTSERVICE_QNAME, features);
    }

    public CountryPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CountryPort
     */
    @WebEndpoint(name = "CountryPortSoap11")
    public CountryPort getCountryPortSoap11() {
        return super.getPort(new QName("http://locahost:8090", "CountryPortSoap11"), CountryPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryPort
     */
    @WebEndpoint(name = "CountryPortSoap11")
    public CountryPort getCountryPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://locahost:8090", "CountryPortSoap11"), CountryPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYPORTSERVICE_EXCEPTION!= null) {
            throw COUNTRYPORTSERVICE_EXCEPTION;
        }
        return COUNTRYPORTSERVICE_WSDL_LOCATION;
    }

}
