
package dinhnguyen.techs.convert.mapper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CountryService", targetNamespace = "http://locahost:8090", wsdlLocation = "http://localhost:8090/soap/country.wsdl")
public class CountryService
    extends Service
{

    private final static URL COUNTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException COUNTRYSERVICE_EXCEPTION;
    private final static QName COUNTRYSERVICE_QNAME = new QName("http://locahost:8090", "CountryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/soap/country.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COUNTRYSERVICE_WSDL_LOCATION = url;
        COUNTRYSERVICE_EXCEPTION = e;
    }

    public CountryService() {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME);
    }

    public CountryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME);
    }

    public CountryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COUNTRYSERVICE_QNAME, features);
    }

    public CountryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Country
     */
    @WebEndpoint(name = "CountrySoap11")
    public Country getCountrySoap11() {
        return super.getPort(new QName("http://locahost:8090", "CountrySoap11"), Country.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Country
     */
    @WebEndpoint(name = "CountrySoap11")
    public Country getCountrySoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://locahost:8090", "CountrySoap11"), Country.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COUNTRYSERVICE_EXCEPTION!= null) {
            throw COUNTRYSERVICE_EXCEPTION;
        }
        return COUNTRYSERVICE_WSDL_LOCATION;
    }

}
