//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.25 at 11:35:26 AM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://dinhnguyen.techs/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package techs.dinhnguyen.soap;
